---
api.port: 1323
etcd.address: 192.168.1.9:2379
cloud.server.url: "http://192.168.1.9:1324"

offloading: true
scheduler.policy: default
fc_scheduler.policy: edgecloud
container.pool.memory: 3072
scheduler.queue.capacity: 0

tracing.enabled: false
#tracing.outfile: ./tracing/tracing.json

metrics.enabled: true
