---
api.port: 1323
etcd.address: 192.168.1.10:2379
cloud.server.url: "http://192.168.1.10:1324"

offloading: true
scheduler.policy: greedyedgecloud
fc_scheduler.policy: greedyedgecloud
container.pool.memory: 3072
scheduler.queue.capacity: 0

tracing.enabled: true
#tracing.outfile: ./tracing/tracing.json

metrics.enabled: true
