def handler(params, context):
    return extractReviews(params["input"])

def extractReviews(file_path):
    
    positive_reviews = [
        "This product is amazing!", "Absolutely love it, works perfectly.","Great quality and excellent value for money.",
        "Highly recommended, fantastic experience.","I'm very satisfied with this purchase.","Wonderful product, exceeded expectations.",
        "Amazing features and easy to use.","Perfect for my needs, couldn't be happier.","Exceptional build quality, worth every penny.",
        "Five stars, it's just awesome!","Very impressed, would buy again.","Superb design and functionality.",
        "Couldn't ask for more, great item.","The best product I've bought in years.","Completely satisfied, it's a game-changer.",
        "Outstanding performance, highly recommend.","Impressive quality, totally worth it.","Delivers exactly as promised, love it!",
        "Flawless operation, exceeded my expectations.","An excellent investment, works beautifully.","Very happy with this purchase, great product.",
        "Top-notch quality and great service.","It does exactly what it says, amazing.","Thrilled with this, highly recommend.",
        "Perfectly meets my expectations, fantastic.","Love everything about it, no complaints.","Brilliant product, would buy it again.",
        "Great value and excellent quality.","Super happy with this, works perfectly.","Best decision ever, highly recommended.",
        "Really pleased with the results, fantastic.","Couldn't be happier, awesome product.","Does the job wonderfully, very impressed.",
        "Exceeded all my expectations, amazing!","Very reliable, exactly what I needed.","Fantastic purchase, highly satisfied.",
        "Delighted with the quality, just perfect.","Unbeatable quality at this price, amazing.","Works perfectly, couldn't ask for more.",
        "Phenomenal performance, worth every cent.","Simply the best, highly recommend.","Great features, very user-friendly.",
        "Superb experience, love this product.","Very well made, exceeded my expectations.","Couldn't have asked for a better product.",
        "Top-notch item, totally worth it.","Outstanding quality, highly recommend.","Impressive performance, completely satisfied.",
        "Very happy with my purchase, excellent.","Amazing value for the price, just great.","Exactly what I was looking for, perfect.",
        "Exceptional experience, highly recommend.","Wonderful functionality, very impressed.","Great product, couldn't be happier.",
        "Awesome design and quality, fantastic.","Very satisfied, great job!","Absolutely love it, it's perfect.",
        "Five stars, just brilliant.","Highly recommend to everyone, amazing.","Works flawlessly, love this product.",
        "Completely thrilled with this purchase.","The quality is outstanding, highly impressed.", "Fantastic item, worth every penny.",
        "Exceeded my expectations, highly recommend.","Superb functionality, very pleased.","Very reliable and user-friendly, love it.",
        "Outstanding experience, couldn't ask for more.","Highly satisfied, great job.","Perfect quality, love it!",
        "Amazing results, very happy.","Fantastic quality, would buy again.","Super pleased with my decision, great product.",
        "Incredible performance, highly recommend.","Very impressed, it's perfect.","Totally worth it, excellent product.",
        "Wonderful experience, love everything about it.","Outstanding purchase, just brilliant.","Very happy with my decision, amazing product.",
        "Great investment, couldn't be happier.","Fantastic product, exceeded my expectations.","Super happy, works perfectly.",
        "Top-notch quality, highly recommend.","Perfect functionality, love it!","Amazing purchase, completely satisfied.",
        "Very reliable, just what I needed.","Exceptional quality, very pleased.","Absolutely love it, it's just great.",
        "Wonderful product, exceeded all my expectations.","Very pleased with the quality, amazing.","Perfect choice, couldn't be happier.",
        "Fantastic features, highly recommend.", "This product is amazing!", "Absolutely love it, works perfectly.","Great quality and excellent value for money.",
        "Highly recommended, fantastic experience.","I'm very satisfied with this purchase.","Wonderful product, exceeded expectations.",
        "Amazing features and easy to use.","Perfect for my needs, couldn't be happier.","Exceptional build quality, worth every penny.",
        "Five stars, it's just awesome!","Very impressed, would buy again.","Superb design and functionality.",
        "Couldn't ask for more, great item.","The best product I've bought in years.","Completely satisfied, it's a game-changer.",
        "Outstanding performance, highly recommend.","Impressive quality, totally worth it.","Delivers exactly as promised, love it!",
        "Flawless operation, exceeded my expectations.","An excellent investment, works beautifully.","Very happy with this purchase, great product.",
        "Top-notch quality and great service.","It does exactly what it says, amazing.","Thrilled with this, highly recommend.",
        "Perfectly meets my expectations, fantastic.","Love everything about it, no complaints.","Brilliant product, would buy it again.",
        "Great value and excellent quality.","Super happy with this, works perfectly.","Best decision ever, highly recommended.",
        "Really pleased with the results, fantastic.","Couldn't be happier, awesome product.","Does the job wonderfully, very impressed.",
        "Exceeded all my expectations, amazing!","Very reliable, exactly what I needed.","Fantastic purchase, highly satisfied.",
        "Delighted with the quality, just perfect.","Unbeatable quality at this price, amazing.","Works perfectly, couldn't ask for more.",
        "Phenomenal performance, worth every cent.", "Totally unsatisfied, bad experience.","Awful purchase, never again.","Doesn't work as intended, terrible.",
        "Very bad experience, not recommended.","Horrible quality, don't buy this.","Waste of money, absolutely terrible.",
        "Extremely disappointed, bad product.","Completely dissatisfied, poor quality.","Terrible product, not worth the hassle.",
        "Hate it, waste of money.","Bad experience, don't recommend this.","Absolutely terrible, very unsatisfied.",
        "Broke right away, horrible quality.","Completely awful, not worth it.","Terrible customer support, bad experience.",
        "Not happy at all, bad product.","Very disappointed, poor performance.", "Totally unreliable, avoid this.",
        "Awful quality, bad decision.","Horrible experience, terrible quality.","Not as described, very bad product.",
        "Totally disappointed, awful choice.","Waste of time and money, don't buy.","Extremely poor quality, very disappointed.",
        "Terrible build quality, not worth it.","Hate this, don't recommend to anyone.","Bad performance, not worth buying.",
        "Completely dissatisfied, awful experience.","Very poor product, won't buy again.","Terrible design, bad decision.",
        "Horrible performance, not recommended.","Absolutely unreliable, waste of money.","Extremely bad experience, avoid this.",
        "Not happy with this at all, bad choice.","Horrible product, don't waste your money.", "This product is amazing!", "Absolutely love it, works perfectly.","Great quality and excellent value for money.",
        "Highly recommended, fantastic experience.","I'm very satisfied with this purchase.","Wonderful product, exceeded expectations.",
        "Amazing features and easy to use.","Perfect for my needs, couldn't be happier.","Exceptional build quality, worth every penny.",
        "Five stars, it's just awesome!","Very impressed, would buy again.","Superb design and functionality.",
        "Couldn't ask for more, great item.","The best product I've bought in years.","Completely satisfied, it's a game-changer.",
        "Outstanding performance, highly recommend.","Impressive quality, totally worth it.","Delivers exactly as promised, love it!",
        "Flawless operation, exceeded my expectations.","An excellent investment, works beautifully.","Very happy with this purchase, great product.",
        "Top-notch quality and great service.","It does exactly what it says, amazing.","Thrilled with this, highly recommend.",
        "Perfectly meets my expectations, fantastic.","Love everything about it, no complaints.","Brilliant product, would buy it again.",
        "Great value and excellent quality.","Super happy with this, works perfectly.","Best decision ever, highly recommended.",
        "Really pleased with the results, fantastic.","Couldn't be happier, awesome product.","Does the job wonderfully, very impressed.",
        "Exceeded all my expectations, amazing!","Very reliable, exactly what I needed.","Fantastic purchase, highly satisfied.",
        "Delighted with the quality, just perfect.","Unbeatable quality at this price, amazing.","Works perfectly, couldn't ask for more.",
        "Phenomenal performance, worth every cent.","Simply the best, highly recommend.","Great features, very user-friendly.",
        "Superb experience, love this product.","Very well made, exceeded my expectations.","Couldn't have asked for a better product.",
        "Top-notch item, totally worth it.","Outstanding quality, highly recommend.","Impressive performance, completely satisfied.",
        "Very happy with my purchase, excellent.","Amazing value for the price, just great.","Exactly what I was looking for, perfect.",
        "Exceptional experience, highly recommend.","Wonderful functionality, very impressed.","Great product, couldn't be happier.",
        "Awesome design and quality, fantastic.","Very satisfied, great job!","Absolutely love it, it's perfect.",
        "Five stars, just brilliant.","Highly recommend to everyone, amazing.","Works flawlessly, love this product.",
        "Completely thrilled with this purchase.","The quality is outstanding, highly impressed.", "Fantastic item, worth every penny.",
        "Exceeded my expectations, highly recommend.","Superb functionality, very pleased.","Very reliable and user-friendly, love it.",
        "Outstanding experience, couldn't ask for more.","Highly satisfied, great job.","Perfect quality, love it!",
        "Amazing results, very happy.","Fantastic quality, would buy again.", "This product is amazing!", "Absolutely love it, works perfectly.","Great quality and excellent value for money.",
        "Highly recommended, fantastic experience.","I'm very satisfied with this purchase.","Wonderful product, exceeded expectations.",
        "Amazing features and easy to use.","Perfect for my needs, couldn't be happier.","Exceptional build quality, worth every penny.",
        "Five stars, it's just awesome!","Very impressed, would buy again.","Superb design and functionality.",
        "Couldn't ask for more, great item.","The best product I've bought in years.","Completely satisfied, it's a game-changer.",
        "Outstanding performance, highly recommend.","Impressive quality, totally worth it.","Delivers exactly as promised, love it!",
        "Flawless operation, exceeded my expectations.","An excellent investment, works beautifully.","Very happy with this purchase, great product.",
        "Top-notch quality and great service.","It does exactly what it says, amazing.","Thrilled with this, highly recommend.",
        "Perfectly meets my expectations, fantastic.","Love everything about it, no complaints.","Brilliant product, would buy it again.",
        "Great value and excellent quality.","Super happy with this, works perfectly.","Best decision ever, highly recommended.",
        "Really pleased with the results, fantastic.","Couldn't be happier, awesome product.","Does the job wonderfully, very impressed.",
        "Exceeded all my expectations, amazing!","Very reliable, exactly what I needed.","Fantastic purchase, highly satisfied.",
        "Delighted with the quality, just perfect.","Unbeatable quality at this price, amazing.","Works perfectly, couldn't ask for more.",
        "Phenomenal performance, worth every cent.","Simply the best, highly recommend.","Great features, very user-friendly.",
        "Superb experience, love this product.","Very well made, exceeded my expectations.","Couldn't have asked for a better product.",
        "Top-notch item, totally worth it.","Outstanding quality, highly recommend.","Impressive performance, completely satisfied.",
        "Very happy with my purchase, excellent.","Amazing value for the price, just great.","Exactly what I was looking for, perfect.",
        "Exceptional experience, highly recommend.","Wonderful functionality, very impressed.","Great product, couldn't be happier.",
        "Awesome design and quality, fantastic.","Very satisfied, great job!","Absolutely love it, it's perfect.",
        "Five stars, just brilliant.","Highly recommend to everyone, amazing.","Works flawlessly, love this product.",
        "Completely thrilled with this purchase.","The quality is outstanding, highly impressed.", "Fantastic item, worth every penny.",
        "Exceeded my expectations, highly recommend.","Superb functionality, very pleased.","Very reliable and user-friendly, love it.",
        "Outstanding experience, couldn't ask for more.","Highly satisfied, great job.","Perfect quality, love it!",
        "Amazing results, very happy.","Fantastic quality, would buy again.","Super pleased with my decision, great product.",
        "Incredible performance, highly recommend.","Very impressed, it's perfect.","Totally worth it, excellent product.",
        "Wonderful experience, love everything about it.","Outstanding purchase, just brilliant.","Very happy with my decision, amazing product.",
        "Great investment, couldn't be happier.","Fantastic product, exceeded my expectations.","Super happy, works perfectly.",
        "Top-notch quality, highly recommend.","Perfect functionality, love it!","Amazing purchase, completely satisfied.",
        "Very reliable, just what I needed.","Exceptional quality, very pleased.","Absolutely love it, it's just great.",
        "Wonderful product, exceeded all my expectations.","Very pleased with the quality, amazing.","Perfect choice, couldn't be happier.",
        "Fantastic features, highly recommend.", "This product is amazing!", "Absolutely love it, works perfectly.","Great quality and excellent value for money.",
        "Highly recommended, fantastic experience.","I'm very satisfied with this purchase.","Wonderful product, exceeded expectations.",
        "Amazing features and easy to use.","Perfect for my needs, couldn't be happier.","Exceptional build quality, worth every penny.",
        "Five stars, it's just awesome!","Very impressed, would buy again.","Superb design and functionality.",
        "Couldn't ask for more, great item.","The best product I've bought in years.","Completely satisfied, it's a game-changer.",
        "Outstanding performance, highly recommend.","Impressive quality, totally worth it.","Delivers exactly as promised, love it!",
        "Flawless operation, exceeded my expectations.","An excellent investment, works beautifully.","Very happy with this purchase, great product.",
        "Top-notch quality and great service.","It does exactly what it says, amazing.","Thrilled with this, highly recommend.",
        "Perfectly meets my expectations, fantastic.","Love everything about it, no complaints.","Brilliant product, would buy it again.",
        "Great value and excellent quality.","Super happy with this, works perfectly.","Best decision ever, highly recommended.",
        "Really pleased with the results, fantastic.","Couldn't be happier, awesome product.","Does the job wonderfully, very impressed.",
        "Exceeded all my expectations, amazing!","Very reliable, exactly what I needed.","Fantastic purchase, highly satisfied.",
        "Delighted with the quality, just perfect.","Unbeatable quality at this price, amazing.","Works perfectly, couldn't ask for more.",
        "Phenomenal performance, worth every cent.", "This product is amazing!", "Absolutely love it, works perfectly.","Great quality and excellent value for money.",
        "Highly recommended, fantastic experience.","I'm very satisfied with this purchase.","Wonderful product, exceeded expectations.",
        "Amazing features and easy to use.","Perfect for my needs, couldn't be happier.","Exceptional build quality, worth every penny.",
        "Five stars, it's just awesome!","Very impressed, would buy again.","Superb design and functionality.",
        "Couldn't ask for more, great item.","The best product I've bought in years.","Completely satisfied, it's a game-changer.",
        "Outstanding performance, highly recommend.","Impressive quality, totally worth it.","Delivers exactly as promised, love it!",
        "Flawless operation, exceeded my expectations.","An excellent investment, works beautifully.","Very happy with this purchase, great product.",
        "Top-notch quality and great service.","It does exactly what it says, amazing.","Thrilled with this, highly recommend.",
        "Perfectly meets my expectations, fantastic.","Love everything about it, no complaints.","Brilliant product, would buy it again.",
        "Great value and excellent quality.","Super happy with this, works perfectly.","Best decision ever, highly recommended.",
        "Really pleased with the results, fantastic.","Couldn't be happier, awesome product.","Does the job wonderfully, very impressed.",
        "Exceeded all my expectations, amazing!","Very reliable, exactly what I needed.","Fantastic purchase, highly satisfied.",
        "Delighted with the quality, just perfect.","Unbeatable quality at this price, amazing.","Works perfectly, couldn't ask for more.",
        "Phenomenal performance, worth every cent.","Simply the best, highly recommend.","Great features, very user-friendly.",
        "Superb experience, love this product.","Very well made, exceeded my expectations.","Couldn't have asked for a better product.",
        "Top-notch item, totally worth it.","Outstanding quality, highly recommend.","Impressive performance, completely satisfied.",
        "Very happy with my purchase, excellent.","Amazing value for the price, just great.","Exactly what I was looking for, perfect.",
        "Exceptional experience, highly recommend.","Wonderful functionality, very impressed.","Great product, couldn't be happier.",
        "Awesome design and quality, fantastic.","Very satisfied, great job!","Absolutely love it, it's perfect.",
        "Five stars, just brilliant.","Highly recommend to everyone, amazing.","Works flawlessly, love this product.",
        "Completely thrilled with this purchase.","The quality is outstanding, highly impressed.", "Fantastic item, worth every penny.",
        "Exceeded my expectations, highly recommend.","Superb functionality, very pleased.","Very reliable and user-friendly, love it.",
        "Outstanding experience, couldn't ask for more.","Highly satisfied, great job.","Perfect quality, love it!",
        "Amazing results, very happy.","Fantastic quality, would buy again.","Super pleased with my decision, great product.",
        "Incredible performance, highly recommend.","Very impressed, it's perfect.","Totally worth it, excellent product.",
        "Wonderful experience, love everything about it.","Outstanding purchase, just brilliant.","Very happy with my decision, amazing product.",
        "Great investment, couldn't be happier.","Fantastic product, exceeded my expectations.","Super happy, works perfectly.",
        "Top-notch quality, highly recommend.","Perfect functionality, love it!","Amazing purchase, completely satisfied.",
        "Very reliable, just what I needed.","Exceptional quality, very pleased.","Absolutely love it, it's just great.",
        "Wonderful product, exceeded all my expectations.","Very pleased with the quality, amazing.","Perfect choice, couldn't be happier.",
        "Fantastic features, highly recommend.", "This product is amazing!", "Absolutely love it, works perfectly.","Great quality and excellent value for money.",
        "Highly recommended, fantastic experience.","I'm very satisfied with this purchase.","Wonderful product, exceeded expectations.",
        "Amazing features and easy to use.","Perfect for my needs, couldn't be happier.","Exceptional build quality, worth every penny.",
        "Five stars, it's just awesome!","Very impressed, would buy again.","Superb design and functionality.",
        "Couldn't ask for more, great item.","The best product I've bought in years.","Completely satisfied, it's a game-changer.",
        "Outstanding performance, highly recommend.","Impressive quality, totally worth it.","Delivers exactly as promised, love it!",
        "Flawless operation, exceeded my expectations.","An excellent investment, works beautifully.","Very happy with this purchase, great product.",
        "Top-notch quality and great service.","It does exactly what it says, amazing.","Thrilled with this, highly recommend.",
        "Perfectly meets my expectations, fantastic.","Love everything about it, no complaints.","Brilliant product, would buy it again.",
        "Great value and excellent quality.","Super happy with this, works perfectly.","Best decision ever, highly recommended.",
        "Really pleased with the results, fantastic.","Couldn't be happier, awesome product.","Does the job wonderfully, very impressed.",
        "Exceeded all my expectations, amazing!","Very reliable, exactly what I needed.","Fantastic purchase, highly satisfied.",
        "Delighted with the quality, just perfect.","Unbeatable quality at this price, amazing.","Works perfectly, couldn't ask for more.",
        "Phenomenal performance, worth every cent.","This product is amazing!", "Absolutely love it, works perfectly.","Great quality and excellent value for money.",
        "Highly recommended, fantastic experience.","I'm very satisfied with this purchase.","Wonderful product, exceeded expectations.",
        "Amazing features and easy to use.","Perfect for my needs, couldn't be happier.","Exceptional build quality, worth every penny.",
        "Five stars, it's just awesome!","Very impressed, would buy again.","Superb design and functionality.",
        "Couldn't ask for more, great item.","The best product I've bought in years.","Completely satisfied, it's a game-changer.",
        "Outstanding performance, highly recommend.","Impressive quality, totally worth it.","Delivers exactly as promised, love it!",
        "Flawless operation, exceeded my expectations.","An excellent investment, works beautifully.","Very happy with this purchase, great product.",
        "Top-notch quality and great service.","It does exactly what it says, amazing.","Thrilled with this, highly recommend.",
        "Perfectly meets my expectations, fantastic.","Love everything about it, no complaints.","Brilliant product, would buy it again.",
        "Great value and excellent quality.","Super happy with this, works perfectly.","Best decision ever, highly recommended.",
        "Really pleased with the results, fantastic.","Couldn't be happier, awesome product.","Does the job wonderfully, very impressed.",
        "Exceeded all my expectations, amazing!","Very reliable, exactly what I needed.","Fantastic purchase, highly satisfied.",
        "Delighted with the quality, just perfect.","Unbeatable quality at this price, amazing.","Works perfectly, couldn't ask for more.",
        "Phenomenal performance, worth every cent.","Simply the best, highly recommend.","Great features, very user-friendly.",
        "Superb experience, love this product.","Very well made, exceeded my expectations.","Couldn't have asked for a better product.",
        "Top-notch item, totally worth it.","Outstanding quality, highly recommend.","Impressive performance, completely satisfied.",
        "Very happy with my purchase, excellent.","Amazing value for the price, just great.","Exactly what I was looking for, perfect.",
        "Exceptional experience, highly recommend.","Wonderful functionality, very impressed.","Great product, couldn't be happier.",
        "Awesome design and quality, fantastic.","Very satisfied, great job!","Absolutely love it, it's perfect.",
        "Five stars, just brilliant.","Highly recommend to everyone, amazing.","Works flawlessly, love this product.",
        "Completely thrilled with this purchase.","The quality is outstanding, highly impressed.", "Fantastic item, worth every penny.",
        "Exceeded my expectations, highly recommend.","Superb functionality, very pleased.","Very reliable and user-friendly, love it.",
        "Outstanding experience, couldn't ask for more.","Highly satisfied, great job.","Perfect quality, love it!",
        "Amazing results, very happy.","Fantastic quality, would buy again.","Super pleased with my decision, great product.",
        "Incredible performance, highly recommend.","Very impressed, it's perfect.","Totally worth it, excellent product.",
        "Wonderful experience, love everything about it.","Outstanding purchase, just brilliant.","Very happy with my decision, amazing product.",
        "Great investment, couldn't be happier.","Fantastic product, exceeded my expectations.","Super happy, works perfectly.",
        "Top-notch quality, highly recommend.","Perfect functionality, love it!","Amazing purchase, completely satisfied.",
        "Very reliable, just what I needed.","Exceptional quality, very pleased.","Absolutely love it, it's just great.",
        "Wonderful product, exceeded all my expectations.","Very pleased with the quality, amazing.","Perfect choice, couldn't be happier.",
        "Fantastic features, highly recommend.", "This product is amazing!", "Absolutely love it, works perfectly.","Great quality and excellent value for money.",
        "Highly recommended, fantastic experience.","I'm very satisfied with this purchase.","Wonderful product, exceeded expectations.",
        "Amazing features and easy to use.","Perfect for my needs, couldn't be happier.","Exceptional build quality, worth every penny.",
        "Five stars, it's just awesome!","Very impressed, would buy again.","Superb design and functionality.",
        "Couldn't ask for more, great item.","The best product I've bought in years.","Completely satisfied, it's a game-changer.",
        "Outstanding performance, highly recommend.","Impressive quality, totally worth it.","Delivers exactly as promised, love it!",
        "Flawless operation, exceeded my expectations.","An excellent investment, works beautifully.","Very happy with this purchase, great product.",
        "Top-notch quality and great service.","It does exactly what it says, amazing.","Thrilled with this, highly recommend.",
        "Perfectly meets my expectations, fantastic.","Love everything about it, no complaints.","Brilliant product, would buy it again.",
        "Great value and excellent quality.","Super happy with this, works perfectly.","Best decision ever, highly recommended.",
        "Really pleased with the results, fantastic.","Couldn't be happier, awesome product.","Does the job wonderfully, very impressed.",
        "Exceeded all my expectations, amazing!","Very reliable, exactly what I needed.","Fantastic purchase, highly satisfied.",
        "Delighted with the quality, just perfect.","Unbeatable quality at this price, amazing.","Works perfectly, couldn't ask for more.",
        "Phenomenal performance, worth every cent."
    ]

    return positive_reviews